### ISSUE TITLE
compilation error when using tinygo.org/x/drivers/espat/mqtt

### ISSUE THREAD

**Issue by titimoby** [tinygo-org/drivers#100]
During GDG Europe Summit, a tinygo workshop was nicely handled by @deadprogram and @conejoninja (thanks a lot guys)

The last step involved MQTT but some environments couldn't compile the code.

The issue is here:
https://github.com/hybridgroup/gdg-2019/issues/6

The code involved here:
https://github.com/hybridgroup/gdg-2019/blob/master/sensor/arduino/step7/main.go

I post it here because I suspect it is something that espat/mqtt driver but feel free to close it if I'm wrong.

**Comment by deadprogram** [comment]
Anyone else able to reproduce this one? I have not been able to myself yet.

**Comment by deadprogram** [comment]
https://github.com/tinygo-org/tinygo/pull/787 should have fixed that, so I am now closing as that code was merged into TinyGo `dev` branch.

Thank you!
