### ISSUE TITLE
Implementation of shift output register using GPIO

### ISSUE THREAD

**Issue by simulot** [tinygo-org/drivers#134]
Hi,

I'm learning nucelo board using devices taken for an arduino discovery kit.

I have implemented a driver for SN74HC595 register using 3 GPIO. 
I have tested the driver on following MCUs:
- Arduino Uno R3
- Nucleo F103RB

The driver code at: https://github.com/simulot/drivers, branch shiftregister, sub directory shiftregister.

A demo program at https://github.com/simulot/tinygo-chaser

Does it worth to open a pull request for an integration on the Drivers repo?
 
++ simulot

**Comment by conejoninja** [comment]
Hi simulot, yes, totally do the PR. I'll close this issue, so the conversation could continue on the PR itself.
