### ISSUE TITLE
"shiftregister" driver should probably be named "SN74AXXX"

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/drivers#136]
Since this driver really pertains mostly to the SN74AXXX family of shift register chips, should it be renamed to this?

**Comment by conejoninja** [comment]
The code is generic enough, other families should work too like 74HC/HCT595 , STP16C596 , M74HC595 , .... maybe we should rename _shifter_ to avoid confussion: shiftPISO - shiftSIPO ¿?

**Comment by deadprogram** [comment]
Closing due to age.
