### ISSUE TITLE
Need a way to override the default I2C address

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/drivers#14]
There are several cases where an i2c device can have an alternative i2c address, due to manufacturer settings or variation, or my user jumper settings.

Perhaps this could be changing:

```go
type Device struct {
	bus machine.I2C
        Address uint16
}

func New(bus machine.I2C) Device {
	return Device{bus: bus, Address: Address}
}
```

Which would allow user to do something like this:

```go
sensor := mag3110.New(machine.I2C0)
sensor.Address = 0xC2 // some alternative if needed
sensor.Configure()
```

We have to change the usage of `Address` in the methods to `d.Address` as well.

**Comment by aykevl** [comment]
This sounds like a good idea!
Of course, this depends on device support but as far as I know most devices have some way to adjust the I2C address.

**Comment by deadprogram** [comment]
Also, sometime "clones" use a different address. I recall that being the case with some MPU6050s and BMP180's that I have gotten from Alibaba.

**Comment by deadprogram** [comment]
This is now in the `master` branch. Closing.
