### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/drivers#18]
We need to have a way to run tests against these drivers...

**Comment by deadprogram** [comment]
If we were to run "smoke" tests by building the example for each driver, what would be the best way to do this? Download the latest released pre-built binary version of TinyGo from https://github.com/tinygo-org/tinygo/releases or build a dev version from source, or ?

**Comment by aykevl** [comment]
I think downloading the release is both faster and more reliable.

**Comment by deadprogram** [comment]
I have implemented the build of one example per driver as a smoke test. Build is located here: https://circleci.com/gh/tinygo-org/drivers

I will leave this issue open, as we still need more automated tests, this is just a starting point.
