### ISSUE TITLE
Waveshare EPD 4.2" driver

### ISSUE THREAD

**Issue by timboldt** [tinygo-org/drivers#181]
I wrote a driver for the Waveshare 4.2" EPD, since one didn't exist. You can find it here: https://github.com/timboldt/epaper-display/tree/master/v1/epd4in2

If there is interest, I could clean it up and submit it as a PR for this repo.

**Comment by conejoninja** [comment]
Hello @timboldt , it will be great if you submit this driver. New drivers are always welcome. Remember to do the PR against `dev branch` .

**Comment by timboldt** [comment]
Sounds good. https://github.com/tinygo-org/drivers/pull/183

**Comment by deadprogram** [comment]
This was released with v0.14 of drivers, so now closing. Thanks @timboldt
