### ISSUE TITLE
Draw text on LCD

### ISSUE THREAD

**Issue by mcrosson** [tinygo-org/drivers#192]
I've been reviewing the various LCD drivers in this repo and cannot find a mechanism defined for drawing text on an LCD. Is this a supported feature?

**Comment by conejoninja** [comment]
Hello, for drawing text or primitives on displays you could use tinyfont https://github.com/tinygo-org/tinyfont and tinydraw https://github.com/tinygo-org/tinydraw .

**Comment by loraxipam** [comment]
You can also look in the examples.

./examples/hd44780/text/main.go

**Comment by mcrosson** [comment]
Thank you!
