### ISSUE TITLE
hcsr04 driver always returns distance as Zero

### ISSUE THREAD

**Issue by manojpawar94** [tinygo-org/drivers#250]
hcsr04 driver always returns distance as Zero. I am running my program on Arduino Uno. I am getting accurate distance when I code using the Arduino C.

**Comment by conejoninja** [comment]
Unless something has changed, ultrasonic distance sensor is not currently supported on AVR (Arduino UNO)

More info: https://github.com/tinygo-org/drivers/issues/223
