### ISSUE TITLE
examples/wifinina/tlsclient failed

### ISSUE THREAD

**Issue by sago35** [tinygo-org/drivers#290]
If the URL is changed to the following, no error will be displayed.

* www.google.com
* github.com

The environment is as follows.

* windows10
* pyportal + NINA_W102-1.7.4.bin
* tinygo-org/drivers dev (9234d7d9ffee39a7eb83239a90aed15f288655cf)
* tinygo e834d7887143fc8da542d3d29907e8db7a5b9bb2 (2021/07/16)

```
$ tinygo flash --target pyportal --size short --programmer jlink ./examples/wifinina/tlsclient/
```

```
Connecting to XXXXXX
Connection status: No SSID Available
Connection status: No SSID Available
Connection status: No SSID Available
Connection status: No SSID Available
Connection status: No SSID Available
Connected.
192.168.1.123

---------------
Dialing TCP connection
Connection failed: wifinina error: 0x01
```

**Comment by scottfeldman** [comment]
Just a note for now: this is fixed in netdev

**Comment by deadprogram** [comment]
Closing since no longer valid. Thanks everyone!
