### ISSUE TITLE
target pall on

### ISSUE THREAD

**Issue by shayulei** [tinygo-org/drivers#302]
tinygo build -o ./dht11.hex -size=short -target=d1mini .
# tinygo.org/x/drivers/dht
../../../../../../../../root/Documents/GoprojectLinux/pkg/mod/tinygo.org/x/drivers@v0.17.1/dht/constants.go:105:10: undeclared name: counter
../../../../../../../../root/Documents/GoprojectLinux/pkg/mod/tinygo.org/x/drivers@v0.17.1/dht/constants.go:112:29: undeclared name: counter
../../../../../../../../root/Documents/GoprojectLinux/pkg/mod/tinygo.org/x/drivers@v0.17.1/dht/thermometer.go:158:47: undeclared name: counter
../../../../../../../../root/Documents/GoprojectLinux/pkg/mod/tinygo.org/x/drivers@v0.17.1/dht/thermometer.go:170:40: undeclared name: counter
../../../../../../../../root/Documents/GoprojectLinux/pkg/mod/tinygo.org/x/drivers@v0.17.1/dht/util.go:18:49: undeclared name: counter
../../../../../../../../root/Documents/GoprojectLinux/pkg/mod/tinygo.org/x/drivers@v0.17.1/dht/constants.go:115:9: undeclared name: counter
../../../../../../../../root/Documents/GoprojectLinux/pkg/mod/tinygo.org/x/drivers@v0.17.1/dht/thermometer.go:127:21: undeclared name: counter
../../../../../../../../root/Documents/GoprojectLinux/pkg/mod/tinygo.org/x/drivers@v0.17.1/dht/thermometer.go:160:10: UART1 not declared by package machine
../../../../../../../../root/Documents/GoprojectLinux/pkg/mod/tinygo.org/x/drivers@v0.17.1/dht/thermometer.go:161:16: UART1 not declared by package machine
../../../../../../../../root/Documents/GoprojectLinux/pkg/mod/tinygo.org/x/drivers@v0.17.1/dht/util.go:19:9: undeclared name: counter

**Comment by sago35** [comment]
Same problem as #301.
I think #304 solves it a bit.

* d1mini has less memory, so it is better not to use the `fmt` package
* The UART1 part is a board-dependent code and needs to be modified. You will need to consider how to fix it separately. If interrupts are really a problem, functions like `arm.DisableInterrupts()` are needed, but there may not be any for d1mini right now.
    * https://github.com/tinygo-org/drivers/blob/1cbf1a6f3d2c9758bfe0063e8b55be77d1890c49/dht/thermometer.go#L160-L161
    * https://github.com/tinygo-org/tinygo/blob/64d048c47c95bc0a70b4cff109afc1f9039705a4/src/device/arm/arm.go#L177-L182
