### ISSUE TITLE
ws2812 is capping color.RGBA values

### ISSUE THREAD

**Issue by 0xDEAD** [tinygo-org/drivers#326]
color.RGBA uses 16 bit values for the individual components while ws2812 LEDs only have 8 bit values.
ws2812/ws2812.go is pasing the values directly to (8 bit based) function WriteByte:
```
d.WriteByte(color.G) // green
d.WriteByte(color.R) // red
d.WriteByte(color.B) // blue
```
which drops the *upper* byte. This is wrong, as it would write a value of 0xFF00 (almost fully saturated color) as 0x00 (LED off).
A loop over all possible values on color.RGBA.R would not fade the saturation once (as one would expect) but create 256 fades from 0 to 0xFF.

I suggest to drop the usage of types from color here completely and use uint8 instead. In case RGBA should be used, a `>> 8` is required.

**Comment by aykevl** [comment]
No, `color.RGBA` consists of 8 bit values, not 16-bit values: https://pkg.go.dev/image/color#RGBA

I think you are confusing the `RGBA` method, which multiplies each component by 257 to get the 16-bit value.

I think this is working as intended.

**Comment by 0xDEAD** [comment]
Ohhh, you are right. Thanks for the clarification!
