### ISSUE TITLE
Using on Pi Zero W?

### ISSUE THREAD

**Issue by bemble** [tinygo-org/drivers#329]
Hi,

Just a dummy question, can I use the drivers for a GO project running on a Raspberry Pi Zero W?
I have a HR-SC04 sensor and a SSD1306 screen plugged on the PI and want to play with it in GO. I would like to use these drivers instead of other beta-for-years/not-really-maintained libraries.

Thanks.

Project: I developed an alarm clock in Python and I would like to migrate to Go

**Comment by soypat** [comment]
Well yes! Most, if not all, drivers in `tinygo-org/drivers` use interfaces to abstract all I/O. In your case you'd use either the [`NewSPI`](https://github.com/tinygo-org/drivers/blob/release/ssd1306/ssd1306.go#L66) or [`NewI2C`](https://github.com/tinygo-org/drivers/blob/release/ssd1306/ssd1306.go#L56) to control the display. These functions take interfaces which in your case would be a SPI or I2C bus handler from another library. I believe `periph.io` may solve your problem. I'd suggest you join the slack channel over at https://invite.slack.golangbridge.org for better support!

**Comment by aykevl** [comment]
We would like to support this, but I don't think this is currently really doable. The machine package is still used by a lot of drivers. See https://github.com/tinygo-org/drivers/issues/331#issuecomment-948582485.

**Comment by bemble** [comment]
> Well yes! Most, if not all, drivers in `tinygo-org/drivers` use interfaces to abstract all I/O. In your case you'd use either the [`NewSPI`](https://github.com/tinygo-org/drivers/blob/release/ssd1306/ssd1306.go#L66) or [`NewI2C`](https://github.com/tinygo-org/drivers/blob/release/ssd1306/ssd1306.go#L56) to control the display. These functions take interfaces which in your case would be a SPI or I2C bus handler from another library. I believe `periph.io` may solve your problem. I'd suggest you join the slack channel over at https://invite.slack.golangbridge.org for better support!

Thanks for the inputs, I'll do some tests but I will probably end up using `periph.io`.

> We would like to support this, but I don't think this is currently really doable. The machine package is still used by a lot of drivers. See [#331 (comment)](https://github.com/tinygo-org/drivers/issues/331#issuecomment-948582485).

Thanks for the reply and agree, the only way to use drivers without `machine` package is to find a way to abstract it. In my case, `periph.io` might be the solution.

**Comment by icanc0** [comment]
`periph.io` still uses sysfs, and that seems to be deprecated?
