### ISSUE TITLE
Si5351 Bounty

### ISSUE THREAD

**Issue by ghost** [tinygo-org/drivers#366]
Hi
If anyone is interested in doing a bounty to write a si5351 driver please let me know.
This is the driver in c:

https://github.com/adafruit/Adafruit_Si5351_Library/blob/master/Adafruit_SI5351.cpp

https://www.qrp-labs.com/synth/si5351ademo.html#democode

I can offer 300USD

Thanks

**Comment by ysoldak** [comment]
@conotto wohoo, bounty!

If you are serious about your offer, consider joining our tinygo slack channel.
There are many talented developers and some might be interested.

Slack channel: https://gophers.slack.com/messages/CDJD3SUP6

**Comment by ghost** [comment]
@ysoldak Thanks, i shall do that!
