### ISSUE TITLE
Problem with "go get" through tinygo.org

### ISSUE THREAD

**Issue by jmacwhyte** [tinygo-org/drivers#373]
When I `go get tinygo.org/x/drivers/net`, the downloaded files don't include the `http` directory. It looks like I am not getting the latest version of the repo, which I can see here on Github. Maybe I am missing something about how Go works to fetch packages?

I went into my `go/src/tinygo.org/x` directory, deleted the `drivers` folder, and manually re-cloned it direct from Github instead of using `go get`. That got me all the files, but it doesn't sound right that such a workaround should be required.

**Comment by conejoninja** [comment]
Hello, you should "go get" the whole drivers repo, not an individual driver, this should work 

```bash
go get tinygo.org/x/drivers
```

**Comment by jmacwhyte** [comment]
@conejoninja You are right! Sorry about that, just a stupid mistake on my part while trying to troubleshoot something else.
