### ISSUE TITLE
GPS driver/parser trigger panic

### ISSUE THREAD

**Issue by ipsusila** [tinygo-org/drivers#417]
I tested GPS driver/parser and it's trigger panic, due to `index out of range`. 
The problem is in the [gpsparse.go line 103](https://github.com/tinygo-org/drivers/blob/release/gps/gpsparser.go#L103). 
It should be written as

```go
ms, _ := strconv.ParseInt(val[7:9], 10, 16)
```

since the length of NMEA time field (`hhmmss.ss`) is 9 bytes.

Putu

**Comment by deadprogram** [comment]
Sorry about the slow response @ipsusila I think you are correct! Would you be able to submit a PR with the correction?

**Comment by deadprogram** [comment]
I think this specific issue was addressed by several changes to GPS parser, so now closing. Thanks!
