### ISSUE TITLE
Driver for GC9A01 Display

### ISSUE THREAD

**Issue by lmatte7** [tinygo-org/drivers#442]
Hello! I'd like to contribute a new driver for the [GC9A01](https://www.waveshare.com/1.28inch-lcd-module.htm) driver for a round display. I've started some preliminary work, but wanted to open an issue first to make sure I wasn't duplicating any other work (per the `CONTRIBUTING.md` file.

**Comment by deadprogram** [comment]
Round display? Cool... Yes, please, and thank you!

**Comment by rcbadiale** [comment]
Hey lmatte7, I was going to start looking into this display, did you had any progress?

If you need any help please let me know.

**Comment by lmatte7** [comment]
I did make some progress! There’s a PR merged now that’s waiting for a release https://github.com/tinygo-org/drivers/pull/452

**Comment by rcbadiale** [comment]
Cool! I didn't noticed it in dev, sorry for bothering!

I will take a look at what you've done.

Thank you very much for your work!

**Comment by lmatte7** [comment]
No worries! I’m glad there are some other people using these cool little displays 😄

**Comment by lmatte7** [comment]
Oh I didn't realize this was still open! Closing since it was resolved with #452
