### ISSUE TITLE
Dallas onewire (ds18b20 temperature sensor) feature request

### ISSUE THREAD

**Issue by s-fairchild** [tinygo-org/drivers#490]
Hello,

Is it possible that Dallas Onewire communication be added?
I'm interested in using Tinygo with a ds18b20 temperature sensor.
All the Go libraries I've found depend on a host driver/OS.

Thank you.

**Comment by conejoninja** [comment]
Closing this because it's a duplicated of #489

Answering your question, yes it should be possible to add a DS18B20 driver

**Comment by s-fairchild** [comment]
@conejoninja Thank you
