### ISSUE TITLE
Add a driver for ams AS5600

### ISSUE THREAD

**Issue by neildavis** [tinygo-org/drivers#510]
Add driver support for the ams [AS5600](https://ams.com/as5600) & [AS5601](https://ams.com/as5601) magnetic angle measurement/rotary position sensors.

These are nice contactless sensors with a decent resolution (12-bit) and not too expensive. Can be useful as an alternative to potentiometers, rotary encoders etc where you need the full 360 degree range.

They can work via I2C and/or analog/PWM.

**Comment by neildavis** [comment]
@deadprogram I have WIP for this now, so expect a PR soon

**Comment by deadprogram** [comment]
Looking forward to it!

**Comment by neildavis** [comment]
#520 is ready for review :)

**Comment by neildavis** [comment]
@deadprogram Can I get a review please? I'm not sure who to request from, so if you've not got time yourself perhaps you could ask another kind soul? Thanks!

**Comment by deadprogram** [comment]
This was already released so now closing. Thanks!
