### ISSUE TITLE
Arduino-Nano-33-Iot  Mqtt error

### ISSUE THREAD

**Issue by fangyygw** [tinygo-org/drivers#524]
using 

https://github.com/tinygo-org/drivers/tree/release/examples/wifinina/mqttclient
https://github.com/tinygo-org/drivers/tree/release/examples/wifinina/mqttsub

Console the same error

Connecting to WIFI
Connected.
192.168.0.107
Connecting to MQTT broker at tcp://192.168.0.106:1883
wifinina error: 0x01
wifinina error: 0x01
wifinina error: 0x01
wifinina error: 0x01
wifinina error: 0x01
wifinina error: 0x01

https://github.com/tinygo-org/drivers/tree/release/examples/wifinina/tcpclient.  is OK

**Comment by deadprogram** [comment]
I think this is fixed by https://github.com/tinygo-org/drivers/commit/de2742f10cc878a3ec482feb8608e7623e3f9dfa

I am going to tag to close on next release.

**Comment by deadprogram** [comment]
This was already released so now closing. Thanks!
