### ISSUE TITLE
Driver for Adafruit Seesaw & Neotrellis

### ISSUE THREAD

**Issue by trichner** [tinygo-org/drivers#564]
As far as I can see there is currently no support for the Adafruit Seesaw chip which powers a lot of Adafruit boards. Among them the NeoTrellis 4x4 keypad with RGB background lights.

I'd like to add partial support for the Adafruit Seesaw, namely what is used by NeoTrellis as well as NeoTrellis support.

Reference:
- [Neotrellis](https://learn.adafruit.com/adafruit-neotrellis/overview)
- [adafruit-seesaw-atsamd09-breakout.pdf](https://github.com/tinygo-org/drivers/files/11414864/adafruit-seesaw-atsamd09-breakout.pdf)

According to the contribution guidelines I'm supposed to open an issue first :)

Draft implementations:
- https://github.com/trichner/gonybox/tree/main/pkg/seesaw
- https://github.com/trichner/gonybox/tree/main/pkg/neotrellis

Is there already support that I missed?

**Comment by conejoninja** [comment]
Hello!

As far as I know, there's no work on the seesaw yet, so feel free to continue and update this issue once the PR is ready.

Thanks!

**Comment by trichner** [comment]
Thanks for the quick reply, I'll open a PR here as soon as it's 'presentable'.
