### ISSUE TITLE
Problem with go get tinygo.org/x/drivers

### ISSUE THREAD

**Issue by ukd1** [tinygo-org/drivers#645]
Trying to install the drivers does not work on go1.21.1:
```bash
% go get tinygo.org/x/drivers
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
% go install tinygo.org/x/drivers@latest
package tinygo.org/x/drivers is not a main package
%
```

Tried with `tinygo` instead of `go`:
```bash
% tinygo get tinygo.org/x/drivers
Unknown command: get
TinyGo is a Go compiler for small places.
version: 0.30.0
.....
```

My version of go:
```bash
% go version
go version go1.21.1 darwin/arm64
```

Does tinygo require an older version of Go?

**Comment by conejoninja** [comment]
Hello, looks like you are not using modules , try with 

```bash
go mod init example.com/myprogram
go get tinygo.org/x/drivers
```


Here are some more information about how to use modules : 
https://go.dev/blog/using-go-modules


Closing this issue because it's not related to this repo itself (afaik), but to the use of modules. Feel free to keep commenting here is you encounter any other issue related, we'll try to answer despite it being closed.

**Comment by ukd1** [comment]
This is related, as imho [the docs are out of date, or incorrect, or both](https://github.com/tinygo-org/drivers/blob/fd21e6ac9b4a5c3bd906ed8a82783a972be6d4ca/README.md?plain=1#L14), so imho shouldn't have been closed.

@conejoninja : 

* `go get` is depreciated since 2019 / 1.17 - https://go.dev/doc/go-get-install-deprecation.
* I'd expect either that the project explicitly says to use an older version of Go, or document this work around, or support `go install`

Using the install method from the docs in this repo on a fresh project fails. This isn't a good experience. From [the docs](https://github.com/tinygo-org/drivers/blob/fd21e6ac9b4a5c3bd906ed8a82783a972be6d4ca/README.md?plain=1#L14):

## Installing

```shell
go get tinygo.org/x/drivers
```
