### ISSUE TITLE
User servo with Pico

### ISSUE THREAD

**Issue by eleimt** [tinygo-org/drivers#694]
Hello
Tell me please, how use servo.go with Pico? I have this code:
```go
package main

import ...

func main() {
	srv, err := servo.New(machine.PWM0, machine.GP16)
	if err != nil {
		println(err.Error())
	}

	for i := 0; i <= 180; i++ {
		srv.SetAngle(i)
		time.Sleep(time.Millisecond * 2)
	}
}
```

But servo works in jerks..
https://www.friendlywire.com/projects/ne555-servo-safe/SG90-datasheet.pdf

![video_2024-07-19_20-50-15](https://github.com/user-attachments/assets/e4ebaac6-fb33-405f-8a96-67885650b1d4)

**Comment by deadprogram** [comment]
@eleimt please see Servo example in repo:

https://github.com/tinygo-org/drivers/blob/release/examples/servo/servo.go

**Comment by eleimt** [comment]
@deadprogram The situation has not changed

**Comment by eleimt** [comment]
@deadprogram Hi, thanks, I find problem. Problem was not in code.
