### ISSUE TITLE
dht package is broken

### ISSUE THREAD

**Issue by Gnyblast** [tinygo-org/drivers#696]
Since release [v0.20.0](https://pkg.go.dev/tinygo.org/x/drivers@v0.20.0/dht) when `device.go` introduced to the package, the methods are gone for dht package like: `dht.New()`. dht package now only exposes `device.go` constants and types which just 3 items, as you can see in the image below.

![image](https://github.com/user-attachments/assets/a545882f-27f7-4cf4-a842-2261e61c2b3e)

[v0.19.0](https://pkg.go.dev/tinygo.org/x/drivers@v0.19.0/dht) seem to not having this issue though. 

I don't think I'm doing some miss-implementation because your [example](https://github.com/tinygo-org/drivers/blob/release/examples/dht/main.go) is also using that way which is not exist anymore.

I see when I compare this `dht` package tagged with `//go:build tinygo` any reason doing that? Gopls now does not support it.

**Comment by deadprogram** [comment]
Hello @Gnyblast I think the issue must be with the auto-complete in your editor, since the `dht` package itself builds correctly in the CI.

See https://github.com/tinygo-org/drivers/blob/release/smoketest.sh#L101 and https://github.com/tinygo-org/drivers/actions/runs/9563791661/job/26363092847#step:8:378

Perhaps you need to open an issue in https://github.com/tinygo-org/vscode-tinygo?

**Comment by Gnyblast** [comment]
Yeah since addition of go tags to top `//go:build tinygo`, gopls stopped working.

**Comment by Gnyblast** [comment]
Yeah problem was vscode-tinygo configs from the looks of it. Thanks.

**Comment by Gnyblast** [comment]
Sorry to coming back to this again but let me explain. I'm writing a program for especially for Raspberry pi **(not pico)** models. And I'm not using tinygo because it's obviosuly running an OS not a microcontroller. I just wanted to take advantage of your `drivers` module to create a factory for input devices, communicate and fetch data from them. But obviously since `v0.20.0` the addition of `//go:build tinygo` prevents default `gopls` on vscode to resolve the code correctly also the go compiler as well. This go tag is added because the code is not compatible with main go binary for compilation and being used as library or just to make things more integrated on tinygo side?
