### ISSUE TITLE
Add support for 120MHz M4 chips to ws2812 driver

### ISSUE THREAD

**Issue by bgould** [tinygo-org/drivers#96]
Currently the ws2812 driver does not seem to support 120 MHz Cortex-M4 chips.  It would be nice if support could be added for the benefit of Adafruit Itsy Bitsy M4, Feather M4, Metro M4 etc.  Feather M4 and Metro M4 in particular have one of these LEDs integrated onto the board so a driver would be especially helpful.

**Comment by bgould** [comment]
https://github.com/tinygo-org/drivers/pull/102

**Comment by deadprogram** [comment]
Now closing since #102 has been merged. Thanks!
